// Quest definitions

export const QUESTS = {
  1: {
    id: 1,
    icon: 'posture',
    name: 'Fix Your Posture',
    xp: 5,
    stat: 'physique',
    increment: 1,
  },
  2: {
    id: 2,
    icon: 'eye',
    name: 'Eye Care (20-20-20 rule)',
    xp: 5,
    stat: 'perception',
    increment: 1,
  },
  3: {
    id: 3,
    icon: 'video',
    name: 'Edit & Post 1 YouTube Short',
    xp: 20,
    stat: 'discipline',
    increment: 2,
  },
  4: {
    id: 4,
    icon: 'book',
    name: 'Read 1 Book Chapter',
    xp: 10,
    stats: { discipline: 1, intelligence: 1 },
  },
  5: {
    id: 5,
    icon: 'workout',
    name: 'Workout (Pushups/Pullups/Squats)',
    xp: 15,
    stat: 'physique',
    increment: 2,
  },
  6: {
    id: 6,
    icon: 'code',
    name: 'Solve 1 DSA Problem',
    xp: 15,
    stat: 'intelligence',
    increment: 2,
  },
  7: {
    id: 7,
    icon: 'tech',
    name: 'Study 1 Tech Topic (React/JS/JWT/API)',
    xp: 15,
    stat: 'tech',
    increment: 2,
  },
  8: {
    id: 8,
    icon: 'strategy',
    name: 'Win 1 Chess Match',
    xp: 10,
    stat: 'intelligence',
    increment: 1,
  },
  9: {
    id: 9,
    icon: 'finance',
    name: 'Read Finance (Finshots/ET)',
    xp: 10,
    stat: 'finance',
    increment: 2,
  },
  10: {
    id: 10,
    icon: 'travel',
    name: 'Watch Travel Vlog or Visit a Place',
    xp: 10,
    stat: 'perception',
    increment: 2,
  },
};

export const ACHIEVEMENTS = {
  'first_blood': {
    id: 'first_blood',
    name: 'First Blood',
    description: 'Complete any quest for the first time',
    icon: 'blood',
    unlocked: false,
  },
  'iron_will': {
    id: 'iron_will',
    name: 'Iron Will',
    description: 'Complete all 10 quests in one day',
    icon: 'shield',
    unlocked: false,
    rarity: 'Legendary',
  },
  '7_day_warrior': {
    id: '7_day_warrior',
    name: '7-Day Warrior',
    description: '7 day streak',
    icon: 'sword',
    unlocked: false,
  },
  'code_monk': {
    id: 'code_monk',
    name: 'Code Monk',
    description: 'Solve DSA 7 days in a row',
    icon: 'terminal',
    unlocked: false,
  },
  'body_of_steel': {
    id: 'body_of_steel',
    name: 'Body of Steel',
    description: 'Complete workouts 10 days in a row',
    icon: 'physique',
    unlocked: false,
  },
  'market_reader': {
    id: 'market_reader',
    name: 'Market Reader',
    description: 'Finance quests 14 days in a row',
    icon: 'finance',
    unlocked: false,
  },
  'shadow_step': {
    id: 'shadow_step',
    name: 'Shadow Step',
    description: 'Reach Level 10',
    icon: 'shadow',
    unlocked: false,
  },
  'monarch': {
    id: 'monarch',
    name: 'Monarch',
    description: 'Reach S rank in any stat',
    icon: 'crown',
    unlocked: false,
    rarity: 'Legendary',
  },
};
